Design
BryggansBryggeri/experimental_ui pull request #7
Opened 2022-10-04 08:19 UTC by FagerJ

2022-10-04 12:05 UTC, FagerJ commented
A lot of small changes. 
There are some things that need to be fixed before merge, but please check them out and give some constructive feedback that you'd like to see before this pull request can be merged.

2022-10-05 19:22 UTC, jackonelli requested changes
Fint!

Det vore önskvärt om PR i framtiden kan vara mindre. Går det att dela upp denna i flera tro, t.ex. en bara för stil (lägga till tailwind et c). Och sen ändra en komponent i taget. Det är svårt att få en överblick över allt det här.

Går det att ha en mapp med statiskt innehåll? Komponentfilerna blir extremt svåra att läsa med ex. rå svg på massa rader.
Måste åtgärdas:
- Linten ger några fel och varningar. Det är inget drastiskt, men det lämnas åt läsaren att lösa som övning. Kör alltid lint/format/check-scripten jag har skapat. De är listade i `package.json`. De kan med fördel läggas in som en commit-hook. Jag har själv slarvat med det men om vi nu båda ska bidra måste det göras annars blir det konflikt-galore.
- Komponenterna är kopplade på något obehagligt globalt sätt: Ändrar jag Man/Auto-mode på ena kontrollern så blinkar den andra till och båda hamnar i mellanläget en kort stund.
- Det har också smugit sig in lite tillstånd i UI:t. Jag kan toggla kontrollern av/på utan kontakt med backend.

2022-10-05 20:52 UTC, FagerJ commented
-> Fortfarande inte perfekt, men lintern klagar bara lite nu.
-> Toggle håller inte längre något state. 
-> Tog bort timeout funktionen, får kika vidare på den senare.

Vissa styles som är brutna nu, men jag fixar.

2022-10-13 13:26 UTC, jackonelli requested changes
- `NavBar` setup component is not done right, see how I use `defineComponent` in the other components.
- The controller modes are now Manual | Temperature, I think they should be Manual | Auto. We shouldn't assume that we always control a temperature.
- Not important now, but when I use the UI in split screen the controller windows randomly change sizes.
- There is a logical error in `ManAutoToggle.vue`, line

2022-10-13 13:26 UTC, jackonelli commented on src/components/ManAutoToggle.vue
> +  if (input == "manual") {
This comparison is incorrect and will always evaluate to false.
Check how I do it in the Controller comp.

2022-10-13 13:26 UTC, jackonelli commented on src/components/ManAutoToggle.vue
> +  } else if (input == "Auto") {
Same error here.

2022-10-28 15:14 UTC, FagerJ commented
HAPPY BIRTHDAY

2023-02-18 09:39 UTC, merged